name: 'leap'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  leap:
    database: ANALYTICS  
    
    staging:
      schema: PROD_STAGING  
      materialized: view
    consolidated:
      schema: PROD_CONSOLIDATED  
      materialized: table


# Full documentation: https://docs.getdbt.com/docs/configuring-models
