
version: 2

models:
    - name: stg_chicago_bike_station_info_flatten
      description: "model built on top of raw data source in snowflake. no transformations performed"
      columns:
          - name: legacy_id
            description: "named as legacy but is used to join with stg_chicago_bike_station_status_flatten_full"
            data_tests:
                - unique
                - not_null

    - name: stg_chicago_bike_station_status_flatten_full
      description: "model built on top of raw data source in snowflake. no transformations performed"
      columns:
          - name: station_id
            description: "the non-unique id for each station"
            data_tests:
                - not_null

    - name: stg_weather_forecast_day
      description: "model built on top of raw data source in snowflake. columns not using the  metric system are transformed"
      columns: 
        - name: date_valid_std
          description: "the date of the forecast"
          data_tests: 
            - not_null
        - name: country
          description: "the location/country of the forecasted weather variables"
          data_tests: 
            - not_null

    - name: stg_weather_history_day
      description: "model built on top of raw data source in snowflake. columns not using the  metric system are transformed"
      columns: 
        - name: date_valid_std
          description: "the date of the measured weather values"
          data_tests: 
            - not_null
        - name: country
          description: "the location/country of the measured weather variables"
          data_tests: 
            - not_null
                