version: 2

sources:
  - name: analytics_raw
    database: analytics
    schema: raw
    tables:
      - name: chicago_bike_station_flatten
      - name: chicago_bike_station_status_flatten_full
      - name: weather_forecast_day
      - name: weather_history_day
